/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_indication_SWC_.c
 * Generated on: Sun Feb 27 16:50:0 EET
 ********************************************************************/

#include "string.h"
#include "Rte_DoorLock_indication_SWC.h"


Rte_DE_myuint8 ReadDoorSensor_PP_SR_DoorState;
Rte_DE_myuint8 DoorLock_indication_RP_SR_DoorState_DoorState;


const Rte_CDS_DoorLock_indication_SWC Rte_Instance_DoorLock_indication_SWC = {
&ReadDoorSensor_PP_SR_DoorState
};

const Rte_CDS_DoorLock_indication_SWC * const Rte_Inst_DoorLock_indication_SWC = &Rte_Instance_DoorLock_indication_SWC;


Std_ReturnType DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode = RTE_E_OK;

FunctionPtr_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate = 0;

myuint8 Rte_IRead_DoorLock_indication_SWC_DoorLock_indication_RP_SR_DoorState_DoorState (void)
{
	return (Rte_Inst_DoorLock_indication_SWC)->DoorLock_indication_RP_SR_DoorState_DoorState->value;
}
Std_ReturnType Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch (myuint8 LedState)
{
	Std_ReturnType __result = DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Buffer_retcode;
	if ( Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate != 0 ) {
		__result = Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_Delegate(LedState);
	}
	//Synch. Implementation to call Direct runnable (Operation)
//	Led_Switch_runnable(LedState);

	Rte_Call_DoorLock_indication_SWC_RP_CS_Led_Switch_Led_Switch_SetEvent(LedState);

	return __result;
}
