/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstactionSWC.h
 * Generated on: Sun Feb 27 16:50:0 EET
 ********************************************************************/

#ifndef RTE_DOORSENSORABSTACTIONSWC_H
#define RTE_DOORSENSORABSTACTIONSWC_H

#include "Rte_DoorSensorAbstactionSWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_DoorSensorAbstactionSWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_DoorSensorAbstactionSWC * const Rte_Inst_DoorSensorAbstactionSWC;

/************************ application errors *************************/

#define RTE_E_IF_CS_LED_E_ok ((Std_ReturnType)0)
#define RTE_E_IF_CS_LED_E_Not_ok ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_SR
 * Interface:	IF_SR_DoorLock
 * DataElement:	DoorState
 * Runnable:	ReadDoorSensor
 *****************************************************/
extern void Rte_IWrite_DoorSensorAbstactionSWC_ReadDoorSensor_PP_SR_DoorState (myuint8 DoorState);
#ifndef IN_RTE_C
#define Rte_IWrite_ReadDoorSensor_PP_SR_DoorState(RTEData) \
	Rte_IWrite_DoorSensorAbstactionSWC_ReadDoorSensor_PP_SR_DoorState(RTEData)
#endif
extern myuint8* Rte_IWriteRef_DoorSensorAbstactionSWC_ReadDoorSensor_PP_SR_DoorState(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_ReadDoorSensor_PP_SR_DoorState() \
	Rte_IWriteRef_DoorSensorAbstactionSWC_ReadDoorSensor_PP_SR_DoorState()
#endif

/*****************************************************
 * Port: 		PP_CS_LEDSwitch
 * Interface:	IF_CS_LED
 * Operation:	Led_Switch
 *****************************************************/
extern Std_ReturnType Led_Switch_runnable(myuint8 LedState) ;


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	ReadDoorSensor
 * Period:		0.01
 *****************************************************/
extern void ReadDoorSensor_runnable(void);

/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORSENSORABSTACTIONSWC_H */
