/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstactionSWC_.c
 * Generated on: Sun Feb 27 16:50:0 EET
 ********************************************************************/

#include "string.h"
#include "Rte_DoorSensorAbstactionSWC.h"


extern Rte_DE_myuint8 ReadDoorSensor_PP_SR_DoorState;


const Rte_CDS_DoorSensorAbstactionSWC Rte_Instance_DoorSensorAbstactionSWC = {
&ReadDoorSensor_PP_SR_DoorState
};

const Rte_CDS_DoorSensorAbstactionSWC * const Rte_Inst_DoorSensorAbstactionSWC = &Rte_Instance_DoorSensorAbstactionSWC;




void Rte_IWrite_DoorSensorAbstactionSWC_ReadDoorSensor_PP_SR_DoorState (myuint8 DoorState)
{
	(Rte_Inst_DoorSensorAbstactionSWC)->ReadDoorSensor_PP_SR_DoorState->value = DoorState;
}
myuint8* Rte_IWriteRef_DoorSensorAbstactionSWC_ReadDoorSensor_PP_SR_DoorState(void)
{
	return &(Rte_Inst_DoorSensorAbstactionSWC)->ReadDoorSensor_PP_SR_DoorState->value;
}
